package model

type AutoGenerated struct {
	Status string `json:"status"`
	Data   Dat    `json:"data"`
}

type Dat struct {
	ResultType string `json:"resultType"`
	Result     []Re   `json:"result"`
}

type Re struct {
	St     []Streams  `json:"stream"`
	Values [][]string `json:"values"`
}

type Streams struct {
	Source string `json:"source"`
}
